
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: clotter_app_development

test:
  <<: *default
  database: clotter_app_test

production:
  <<: *default
  database: clotter_app_production
  username: clotter_app
  password: <%= ENV['CLOTTER_APP_DATABASE_PASSWORD'] %>
